# Generated by Django 5.2.7 on 2026-01-26 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_admin_notes_reservation_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Compound Name'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Unit/House Number'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='months',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
