# Generated by Django 5.2.7 on 2026-01-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Issue/Concern', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_approved', 'Reservation Approved'), ('reservation_denied', 'Reservation Denied'), ('reservation_cancelled', 'Reservation Cancelled'), ('new_message', 'New Message Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
