# Generated by Django 5.2.7 on 2026-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_message_options_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='months',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
