# Generated by Django 5.2.7 on 2026-01-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_approved', 'Reservation Approved'), ('reservation_denied', 'Reservation Denied'), ('reservation_cancelled', 'Reservation Cancelled'), ('new_message', 'New Message Received'), ('new_reservation', 'New Reservation Request')], max_length=30),
        ),
    ]
